using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Dungeon_Crawler_v2.Modul;

namespace Dungeon_Crawler_v2.Modul
{
    internal class Animationer
    {

        public void BombeAnimation()
        {
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓");
            Console.WriteLine("  ▓   ▓      ▓   ▓");
            Console.WriteLine("  ▓   ▓      ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓");
            Console.WriteLine("  ▓   ▓      ▓   ▓");
            Console.WriteLine(" ▓   ▓   ▓▓   ▓   ▓");
            Console.WriteLine(" ▓   ▓   ▓▓   ▓   ▓");
            Console.WriteLine("  ▓   ▓      ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("         ▓▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓");
            Console.WriteLine("  ▓   ▓      ▓   ▓");
            Console.WriteLine(" ▓   ▓   ▓▓   ▓   ▓");
            Console.WriteLine("▓   ▓   ▓  ▓   ▓   ▓");
            Console.WriteLine("▓   ▓   ▓  ▓   ▓   ▓");
            Console.WriteLine(" ▓   ▓   ▓▓   ▓   ▓");
            Console.WriteLine("  ▓   ▓      ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("         ▓▓");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("        ▓  ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓");
            Console.WriteLine("  ▓   ▓      ▓   ▓");
            Console.WriteLine(" ▓   ▓   ▓▓   ▓   ▓");
            Console.WriteLine("▓   ▓   ▓  ▓   ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓   ");
            Console.WriteLine("   ▓   ▓    ▓   ▓   ");
            Console.WriteLine("▓   ▓   ▓  ▓   ▓   ▓");
            Console.WriteLine(" ▓   ▓   ▓▓   ▓   ▓");
            Console.WriteLine("  ▓   ▓      ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("        ▓  ▓");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("       ▓    ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓");
            Console.WriteLine("  ▓   ▓      ▓   ▓");
            Console.WriteLine(" ▓   ▓   ▓▓   ▓   ▓");
            Console.WriteLine("▓   ▓   ▓  ▓   ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓   ");
            Console.WriteLine("  ▓   ▓      ▓   ▓   ");
            Console.WriteLine("  ▓   ▓      ▓   ▓   ");
            Console.WriteLine("   ▓   ▓    ▓   ▓   ▓");
            Console.WriteLine("▓   ▓   ▓  ▓   ▓   ▓");
            Console.WriteLine(" ▓   ▓   ▓▓   ▓   ▓");
            Console.WriteLine("  ▓   ▓      ▓   ▓");
            Console.WriteLine("   ▓   ▓    ▓   ▓");
            Console.WriteLine("    ▓   ▓  ▓   ▓");
            Console.WriteLine("     ▓   ▓▓   ▓");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("       ▓    ▓");
            Thread.Sleep(50);
            Console.Clear();
        }

        public void HelbredeneDrikAnimation()
        {
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓     ▓");
            Console.WriteLine("     ▓▓▓   ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓");
            Console.WriteLine("         ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓▓▓    ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓  ▓▓▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓▓▓    ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓  ▓▓▓▓▓");
            Console.WriteLine("   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓▓▓    ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓  ▓▓▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓     ▓");
            Console.WriteLine("     ▓▓▓   ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓");
            Console.WriteLine("         ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓▓▓    ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓  ▓▓▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓▓▓    ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓  ▓▓▓▓▓");
            Console.WriteLine("   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓▓▓    ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓  ▓▓▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓     ▓");
            Console.WriteLine("     ▓▓▓   ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓");
            Console.WriteLine("         ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓▓▓    ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓  ▓▓▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓▓▓    ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓  ▓▓▓▓▓");
            Console.WriteLine("   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓      ▓");
            Console.WriteLine("     ▓▓▓    ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓  ▓▓▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓▓");
            Console.WriteLine("         ▓▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓     ▓");
            Console.WriteLine("     ▓▓▓   ▓▓▓");
            Console.WriteLine("    ▓▓▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("     ▓▓▓▓▓▓▓▓▓");
            Console.WriteLine("      ▓▓▓▓▓▓▓");
            Console.WriteLine("       ▓▓▓▓▓");
            Console.WriteLine("        ▓▓▓");
            Console.WriteLine("         ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(50);
            Console.Clear();
        }

        public void DobbeltSlagAnimation()
        {
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("                    ");
            Console.WriteLine("                     ");
            Console.WriteLine("                    ");
            Console.WriteLine("                 ");
            Console.WriteLine("                 ");
            Console.WriteLine("                 ");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("                    ");
            Console.WriteLine("                     ");
            Console.WriteLine("                 ");
            Console.WriteLine("                 ");
            Console.WriteLine("                    ");
            Console.WriteLine("                    ");
            Console.WriteLine("           │");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("                    ");
            Console.WriteLine("                     ");
            Console.WriteLine("                 ");
            Console.WriteLine("                 ");
            Console.WriteLine("                    ");
            Console.WriteLine("           │         ");
            Console.WriteLine("           │");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("                    ");
            Console.WriteLine("                     ");
            Console.WriteLine("                 ");
            Console.WriteLine("                 ");
            Console.WriteLine("           │         ");
            Console.WriteLine("           │         ");
            Console.WriteLine("           │");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("                    ");
            Console.WriteLine("                     ");
            Console.WriteLine("                 ");
            Console.WriteLine("           │      ");
            Console.WriteLine("           │         ");
            Console.WriteLine("           │         ");
            Console.WriteLine("       │   │");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("                    ");
            Console.WriteLine("                     ");
            Console.WriteLine("           │      ");
            Console.WriteLine("           │      ");
            Console.WriteLine("           │         ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │   │");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("                    ");
            Console.WriteLine("           │         ");
            Console.WriteLine("           │      ");
            Console.WriteLine("           │      ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │   │");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("           │         ");
            Console.WriteLine("           │         ");
            Console.WriteLine("           │      ");
            Console.WriteLine("       │   │      ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │   │");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("           │         ");
            Console.WriteLine("           │         ");
            Console.WriteLine("       │   │      ");
            Console.WriteLine("       │   │      ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │O══╦══O");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("      ▓    │ ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("           │         ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │   │      ");
            Console.WriteLine("       │   │      ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │O══╦══O         ");
            Console.WriteLine("       │   ║");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓│  ▓     ");
            Console.WriteLine("      ▓    │ ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │   │      ");
            Console.WriteLine("       │   │      ");
            Console.WriteLine("       │O══╦══O   ");
            Console.WriteLine("       │   ║      ");
            Console.WriteLine("       │   O");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓│  ▓     ");
            Console.WriteLine("      ▓     │▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │   │   ");
            Console.WriteLine("       │O══╦══O");
            Console.WriteLine("       │   ║");
            Console.WriteLine("       │   O      ");
            Console.WriteLine("    O══╦══O");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓│  ▓     ");
            Console.WriteLine("      ▓│    │▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓│       ");
            Console.WriteLine("       │    │        ");
            Console.WriteLine("       │   │         ");
            Console.WriteLine("       │O══╦══O      ");
            Console.WriteLine("       │   ║");
            Console.WriteLine("       │   O");
            Console.WriteLine("    O══╦══O         ");
            Console.WriteLine("       ║");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓ │ ▓▓│  ▓     ");
            Console.WriteLine("      ▓│    │▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓│       ");
            Console.WriteLine("       │     │        ");
            Console.WriteLine("       │    │         ");
            Console.WriteLine("       │ O══╦══O      ");
            Console.WriteLine("       │    ║");
            Console.WriteLine("    O══╦══O O");
            Console.WriteLine("       ║      ");
            Console.WriteLine("       O");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓ │ ▓▓│  ▓     ");
            Console.WriteLine("      ▓     │▓      ");
            Console.WriteLine("      │▓▓▓▓▓▓│       ");
            Console.WriteLine("       │    │        ");
            Console.WriteLine("       │    │         ");
            Console.WriteLine("       │    │   ");
            Console.WriteLine("    O══╦══O══╦══O   ");
            Console.WriteLine("       ║     ║");
            Console.WriteLine("       O     O  ");
            Console.WriteLine("            ");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓ │ ▓▓ │ ▓     ");
            Console.WriteLine("      ▓     │▓      ");
            Console.WriteLine("      │▓▓▓▓▓▓       ");
            Console.WriteLine("       │    │        ");
            Console.WriteLine("       │    │         ");
            Console.WriteLine("    O══╦══O │   ");
            Console.WriteLine("       ║    │  ");
            Console.WriteLine("       O O══╦══O");
            Console.WriteLine("            ║  ");
            Console.WriteLine("            O");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓ │ ▓▓   ▓     ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("      │▓▓▓▓▓▓       ");
            Console.WriteLine("       │    │        ");
            Console.WriteLine("    O══╦══O │         ");
            Console.WriteLine("       ║    │   ");
            Console.WriteLine("       O    │  ");
            Console.WriteLine("            │");
            Console.WriteLine("            │  ");
            Console.WriteLine("         O══╦══O");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓ │ ▓▓   ▓     ");
            Console.WriteLine("      ▓│     ▓      ");
            Console.WriteLine("      │▓▓▓▓▓▓       ");
            Console.WriteLine("       │            ");
            Console.WriteLine("       │    │         ");
            Console.WriteLine("    O══╦══O │   ");
            Console.WriteLine("       ║    │  ");
            Console.WriteLine("       O    │");
            Console.WriteLine("            │  ");
            Console.WriteLine("            │");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("      ▓│     ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("       │            ");
            Console.WriteLine("       │            ");
            Console.WriteLine("       │ ");
            Console.WriteLine("    O══╦══O │  ");
            Console.WriteLine("       ║    │");
            Console.WriteLine("       O    │  ");
            Console.WriteLine("            │");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("     ▓   ▓▓   ▓     ");
            Console.WriteLine("      ▓      ▓      ");
            Console.WriteLine("       ▓▓▓▓▓▓       ");
            Console.WriteLine("       │            ");
            Console.WriteLine("       │            ");
            Console.WriteLine("       │ ");
            Console.WriteLine("       │");
            Console.WriteLine("    O══╦══O       ");
            Console.WriteLine("       ║     │  ");
            Console.WriteLine("       O     │");
            Thread.Sleep(20);
            Console.Clear();
        }

        public void FireballAnimation()
        {
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine(" ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("  ▓");
            Console.WriteLine(" ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("   ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("    ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("     ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("      ▓");
            Console.WriteLine("     *");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("       ▓");
            Console.WriteLine("      *");
            Console.WriteLine("     ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("        ▓");
            Console.WriteLine("       *");
            Console.WriteLine("      ");
            Console.WriteLine("     ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("         ▓");
            Console.WriteLine("        *");
            Console.WriteLine("       *");
            Console.WriteLine("      ");
            Console.WriteLine("     ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("         *▓");
            Console.WriteLine("        *");
            Console.WriteLine("       ");
            Console.WriteLine("      ");
            Console.WriteLine("     ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("         **▓");
            Console.WriteLine("        ");
            Console.WriteLine("       ");
            Console.WriteLine("      ");
            Console.WriteLine("     ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("         ***");
            Console.WriteLine("            ▓");
            Console.WriteLine("       ");
            Console.WriteLine("      ");
            Console.WriteLine("     ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("          **");
            Console.WriteLine("            *");
            Console.WriteLine("             ▓");
            Console.WriteLine("      ");
            Console.WriteLine("     ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();


            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("           *");
            Console.WriteLine("            *");
            Console.WriteLine("             *");
            Console.WriteLine("              ▓");
            Console.WriteLine("     ");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("           ");
            Console.WriteLine("            *");
            Console.WriteLine("             *");
            Console.WriteLine("              *");
            Console.WriteLine("               ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("           ");
            Console.WriteLine("            ");
            Console.WriteLine("             *");
            Console.WriteLine("              *");
            Console.WriteLine("               ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("           ");
            Console.WriteLine("            ");
            Console.WriteLine("             ");
            Console.WriteLine("              *");
            Console.WriteLine("               ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("           ");
            Console.WriteLine("            ");
            Console.WriteLine("             ");
            Console.WriteLine("              ");
            Console.WriteLine("               ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("           ");
            Console.WriteLine("            ");
            Console.WriteLine("             ");
            Console.WriteLine("               ▓");
            Console.WriteLine("              ▓*▓");
            Console.WriteLine("               ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("           ");
            Console.WriteLine("            ");
            Console.WriteLine("               ▓");
            Console.WriteLine("              ▓ ▓");
            Console.WriteLine("             ▓ ▓ ▓");
            Console.WriteLine("              ▓ ▓");
            Console.WriteLine("               ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("           ");
            Console.WriteLine("               ▓");
            Console.WriteLine("              ▓*▓");
            Console.WriteLine("             ▓*▓*▓");
            Console.WriteLine("            ▓*▓*▓*▓");
            Console.WriteLine("             ▓*▓*▓");
            Console.WriteLine("              ▓*▓");
            Console.WriteLine("               ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("               ▓");
            Console.WriteLine("              ▓ ▓");
            Console.WriteLine("             ▓ ▓ ▓");
            Console.WriteLine("            ▓ ▓ ▓ ▓");
            Console.WriteLine("           ▓ ▓ ▓ ▓ ▓");
            Console.WriteLine("            ▓ ▓ ▓ ▓");
            Console.WriteLine("             ▓ ▓ ▓");
            Console.WriteLine("              ▓ ▓");
            Console.WriteLine("               ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();

            Console.Clear();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("               ▓");
            Console.WriteLine("              ▓*▓");
            Console.WriteLine("             ▓*▓*▓");
            Console.WriteLine("            ▓*▓*▓*▓");
            Console.WriteLine("           ▓*▓*▓*▓*▓");
            Console.WriteLine("          ▓*▓*▓*▓*▓*▓");
            Console.WriteLine("           ▓*▓*▓*▓*▓");
            Console.WriteLine("            ▓*▓*▓*▓");
            Console.WriteLine("             ▓*▓*▓");
            Console.WriteLine("              ▓*▓");
            Console.WriteLine("               ▓");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(20);
            Console.Clear();
        }
    }
}
